"""initial tables

Revision ID: 78751ef8d841
Revises: 
Create Date: 2026-08-13 17:59:58.794091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78751ef8d841'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iot_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=False),
    sa.Column('voltage_v', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_readings_device_id'), 'iot_readings', ['device_id'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('price_per_kwh', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_prices_region'), 'market_prices', ['region'], unique=False)
    op.create_table('weather_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('wind_speed_ms', sa.Float(), nullable=False),
    sa.Column('solar_irradiance_wm2', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_readings_location'), 'weather_readings', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_readings_location'), table_name='weather_readings')
    op.drop_table('weather_readings')
    op.drop_index(op.f('ix_market_prices_region'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_iot_readings_device_id'), table_name='iot_readings')
    op.drop_table('iot_readings')
    # ### end Alembic commands ###
